# Tensors

A _Tensors_ - a fundamental format in PyTorch is not just a data structure but are also optimized for the mathematical operations that power deep learning. This tutorial shows  various tensor operations including checking tensor shapes, types, or dimensions to help managing the data for any PyTorch project.

In this tutorial,

* Tensors will be created from different data sources like Python lists and NumPy arrays.

* Tensors will be reshaped and its dimensions will be manipulated to prepare data for model inputs.

* Indexing and slicing techniques will be used to access and filter specific parts of the data.

* The mathematical and logical operations that form the basis of all neural network computations will be performed.



## Importing Packages

In [1]:
import torch
import numpy as np
import pandas as pd

## 1. Tensor Creation

The first step in any machine learning pipeline is getting the data ready for the model. In PyTorch, this means loading your data into tensors. There are several convenient ways to create tensors, whether the data is already in another format or it needs to be generated from scratch.


### 1.1 From Existing Data Structures

If the raw data is in a common format like a Python list, a NumPy array, or a pandas DataFrame, PyTorch provides straightforward functions to convert these structures into tensors, making the data preparation stage more efficient as shown below.

**From User Privided List**

In [12]:
# Takes input such as a Python list to convert it into an integer tensor
x = torch.tensor([1, 2, 3])

print("Data:", x)
print("Data type:", x.dtype)

Data: tensor([1, 2, 3])
Data type: torch.int64


**From NumPy Array**

In [10]:
# Converts a NumPy array into a PyTorch tensor
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("Data:\n\n", torch_tensor_from_numpy)

Data:

 tensor([[1, 2, 3],
        [4, 5, 6]])


**From a Pandas DataFrame**

There isn't a direct function to convert a DataFrame to a tensor. The standard method is to extract the data from the DataFrame into a NumPy array using the `.values` attribute, and then convert that array into a tensor using `torch.tensor()`.

In [ ]:
# Reads the data from the CSV file into a Pandas DataFrame
df = pd.read_csv('./datasets/data.csv')

# Converts the numpy values to a PyTorch tensor
tensor_from_df = torch.tensor(df.values)

print("DataFrame Data:\n\n", df)
print("\nTensor:", tensor_from_df)
print("\nData Type:", tensor_from_df.dtype)

DataFrame Data:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

Tensor: tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

Data Type: torch.float64


### 1.2 With Predefined Values

PyTorch allows quick generatation of tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for specific purposes such as initializing a model's weights and biases, testing and setup, etc.

In [8]:
# Creates a tensor filled with zeros of the specified dimensions.
zeros = torch.zeros(2, 3)   # 2 rows, 3 columns

print("Tensor will scaler value zeros:\n\n", zeros)

Tensor will scaler value zeros:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# Creates a tensor filled with ones of the specified dimensions.
ones = torch.ones(2, 3)  # 2 rows, 3 columns

print("Tensor will scaler value ones:\n\n", ones)

Tensor will scaler value ones:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# Generates a tensor with random numbers uniformly distributed between 0 and 1, 
# based on the specified dimensions.
random = torch.rand(2, 3)   # 2 rows, 3 columns

print("tensor filled with random numbers:\n\n", random)

tensor filled with random numbers:

 tensor([[0.7742, 0.5055, 0.2218],
        [0.7587, 0.8177, 0.0419]])


### 1.3 From a Sequence

PyToch also allows to creating tensor with data within a specific range.

In [15]:
# Creates a 1D tensor containing a range of numbers from the specified start value 
# to one less than the specified stop value, incrementing (if positive) or 
# decrementing (if negative) by the specified `step` value.
range_tensor = torch.arange(0, 10, step=1)

print("Range Tensor:", range_tensor)

Range Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2. Reshaping & Manipulating

A very common source of errors in PyTorch projects is a mismatch between the shape of your input data and the shape your model expects. For instance, a model is typically designed to process a batch of data, so even if prediction needs to be made on a single input value, it must be shaped to look like a batch of one.



### 2.1 Checking a Tensor's Dimensions

Checking tensor shape is effective in situation where number of data samples and number of features in each of the sample need to be checked.

In [16]:
# Creates A 2D tensor first
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Returns a `torch.Size` object detailing the size of the tensor along each dimension.
print("\nTensor Shape:", x.shape)


Tensor Shape: torch.Size([2, 3])


### 2.2 Changing a Tensor's Dimensions

A frequent task in neural network modeling is adding a dimension to a single data sample to create a batch of size one for the model, or removing a dimension after a batch operation is complete.

**Adding Dimension**

In [17]:
print("Original Tensor:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Inserts a new dimension at the specified index.
expanded = x.unsqueeze(0)  # Adds dimension at index 0

print("\nTensor with Added Dimension:\n\n", expanded)
print("\nTensor Shape:", expanded.shape)

Original Tensor:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

Tensor with Added Dimension:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Tensor Shape: torch.Size([1, 2, 3])


Tensor shape was changed from `[2, 3]` to `[1, 2, 3]` and the tensor got wrapped in an extra pair of square brackets `[]`

**Removes Dimension**

* **Removing Dimension:** `torch.Tensor.squeeze()` removes dimensions of size 1.
    * *This reverses the unsqueeze operation, removing the `1` from the shape and taking away a pair of outer square brackets*.

In [18]:
print("Expanded Tensor:\n\n", expanded)
print("\nTensor Shape:", expanded.shape)
print("-"*45)

# Removes the first the shape (eventually taking away a pair of outer square brackets 
# that were added it in the previous step during expanding dimension).
squeezed = expanded.squeeze()

print("\nTensor with Dimension Removed:\n\n", squeezed)
print("\nTensor Shape:", squeezed.shape)

Expanded Tensor:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Tensor Shape: torch.Size([1, 2, 3])
---------------------------------------------

Tensor with Dimension Removed:

 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shape: torch.Size([2, 3])


### 2.3 Restructuring

A tensor can also be restructured completely in scenrios such as to match the requirements of a specific layer or operation within your neural network.

**Reshaping**

In [19]:
print("Original Tensor:\n\n", x)
print("\nTensor Shape:", x.shape)
print("-"*45)

# Reshapes the shape of a tensor to the specified dimensions
reshaped = x.reshape(3, 2)

print("\nReshaped Tensor:\n\n", reshaped)
print("\nTensor Shape:", reshaped.shape)

Original Tensor:

 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shape: torch.Size([2, 3])
---------------------------------------------

Reshaped Tensor:

 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tensor Shape: torch.Size([3, 2])


**Transposing**

In [20]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Transposes at the specified dimensions of a tensor
transposed = x.transpose(0, 1)

print("\nTransposed Tensor:\n\n", transposed)
print("\nTensor Shape:", transposed.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

Transposed Tensor:

 tensor([[1, 4],
        [2, 5],
        [3, 6]])

Tensor Shape: torch.Size([3, 2])


### 2.4 Combining Tensors

Combining tensor could be an important requirement in situations such as combining data from different sources or merging separate batches into one larger dataset.

In [21]:
# Creates two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])

tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

# Concatenates tensors along columns (dim=1)
# All tensors must have the same shape in dimensions other than the one being concatenated.
concatenated_tensors = torch.cat((tensor_a, tensor_b), dim=1)


print("Tensor A:\n\n", tensor_a)
print("\nTensor B:\n\n", tensor_b)
print("-"*45)
print("\nConcatenated Tensor (dim=1):\n\n", concatenated_tensors)

Tensor A:

 tensor([[1, 2],
        [3, 4]])

Tensor B:

 tensor([[5, 6],
        [7, 8]])
---------------------------------------------

Concatenated Tensor (dim=1):

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3. Indexing & Slicing

Often times Whether you are grabbing 
 Indexing and slicing tensor are useful tools when a specific parts of a tensor is required, for example, in accessing a single prediction to inspect its value, or separating input features from the labels, or selecting a subset of data for analysis.

### 3.1 - Accessing Elements

A fundamental technique for getting data out of a tensor.

In [23]:
# Creates a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Tensor:\n\n", x)
print("-" * 55)

# Gets a single element at row 1, column 2
single_element_tensor = x[1, 2]

print("\nSingle Element at [1, 2]:", single_element_tensor)
print("-" * 55)

# Gets the entire second row (index 1)
second_row = x[1]

print("\nEntire Row [1]:", second_row)
print("-" * 55)

# Gets the last row
last_row = x[-1]

print("\nThe Last Row ([-1]):", last_row, "\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

Single Element at [1, 2]: tensor(7)
-------------------------------------------------------

Entire Row [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

The Last Row ([-1]): tensor([ 9, 10, 11, 12]) 



**Slicing**

Extracting sub-tensors using notation `[start:end:step]` 

In [24]:
print("Original Tensor:\n\n", x)
print("-" * 55)

# Gets the first two rows
first_two_rows = x[0:2]

print("\nSlicing First Two Rows ([0:2]):\n\n", first_two_rows)
print("-" * 55)

# Gets the third column of all rows
third_column = x[:, 2]

print("\nSlicing the Third Column ([:, 2]]):", third_column)
print("-" * 55)

# Every other column
every_other_col = x[:, ::2]

print("\nEvery Other Column ([:, ::2]):\n\n", every_other_col)
print("-" * 55)

# The last column
last_col = x[:, -1]

print("\nLast Column ([:, -1]):", last_col, "\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

Slicing First Two Rows ([0:2]):

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
-------------------------------------------------------

Slicing the Third Column ([:, 2]]): tensor([ 3,  7, 11])
-------------------------------------------------------

Every Other Column ([:, ::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
-------------------------------------------------------

Last Column ([:, -1]): tensor([ 4,  8, 12]) 



**Combining Indexing & Slicing**

In [25]:
print("Original Tensor:\n\n", x)
print("-" * 55)

# Combining slicing and indexing (First two rows, last two columns)
combined = x[0:2, 2:]

print("\nFirst Two Rows and Last Two Columns ([0:2, 2:]):\n\n", combined, "\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

First Two Rows and Last Two Columns ([0:2, 2:]):

 tensor([[3, 4],
        [7, 8]]) 



**Extracting Value from a Single-element Tensor as a Standard Python Number**

In [27]:
print("Single Element Tensor:", single_element_tensor)
print("-" * 45)

# Extracts the value from a single-element tensor as a standard Python number
value = single_element_tensor.item()

print("\n.item() Extracted Value as a Python Number:", value)
print("Type:", type(value))

Single Element Tensor: tensor(7)
---------------------------------------------

.item() Extracted Value as a Python Number: 7
Type: <class 'int'>


### 3.2 Advanced Indexing

Following advanced indexing techniques can be used for more complex data selection cases such as filtering dataset based on one or more conditions.

In [30]:
print("Original Tensor:\n\n", x)
print("-" * 55)

# Boolean indexing using logical comparisons
mask = x > 6

# Applies Boolean masking
mask_applied = x[mask]

print("Masked Tensor:", mask_applied, "\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
Masked Tensor: tensor([ 7,  8,  9, 10, 11, 12]) 



**Fancy Indexing**

Extracts specific elements in a non-contiguous way Using a tensor of indices.

In [32]:
print("Original Tensor:\n\n", x)
print("-" * 55)

# Fancy indexing

# Gets first and third rows
row_indices = torch.tensor([0, 2])

# Gets second and fourth columns
col_indices = torch.tensor([1, 3]) 

# Gets values at (0,1), (0,3), (2,1), (2,3)
get_values = x[row_indices[:, None], col_indices]

print("\nSpecific Tensor Elements:\n\n", get_values, "\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

Specific Tensor Elements:

 tensor([[ 2,  4],
        [10, 12]]) 



## 4. Mathematical & Logical Operations

Performing tensor operations (mathematical computations) efficiently.

### 4.1 Arithmetic Operations

Performing arithmetic operations element-wise and using broadcasting.

**Element-wise Addition & Multiplication**

In [33]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("Tensor A:", a)
print("Tensor B", b)
print("-" * 60)

# Performs element-wise addition
element_add = a + b

print("\nTensor After Element-wise Addition:", element_add, "\n")

Tensor A: tensor([1, 2, 3])
Tensor B tensor([4, 5, 6])
------------------------------------------------------------

Tensor After Element-wise Addition: tensor([5, 7, 9]) 



In [34]:
print("Tensor A:", a)
print("Tensor B", b)
print("-" * 65)

# Performs element-wise multiplication
element_mul = a * b

print("\nTensor After Element-wise Multiplication:", element_mul, "\n")

Tensor A: tensor([1, 2, 3])
Tensor B tensor([4, 5, 6])
-----------------------------------------------------------------

Tensor After Element-wise Multiplication: tensor([ 4, 10, 18]) 



**Dot Product**: 

In [35]:
print("Tensor A:", a)
print("Tensor B", b)
print("-" * 65)

# Calculates the dot product of two vectors or matrices.
dot_product = torch.matmul(a, b)

print("\nTensor After Performing Dot Product:", dot_product, "\n")

Tensor A: tensor([1, 2, 3])
Tensor B tensor([4, 5, 6])
-----------------------------------------------------------------

Tensor After Performing Dot Product: tensor(32) 



**Broadcasting**

Allowing operations between tensors with incompatible shapes (they don't have the exact same dimensions) by _Broadcasting_ - a technique in which the smaller tensors get expanded automatically to match the shape of larger tensors during arithmetic operations.

In [36]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])

print("Tensor A:", a)
print("Shape of Tensor A:", a.shape)
print("\nTensor B\n\n", b)
print("\nShape of Tensor B:", b.shape)
print("-" * 65)

# Performs broadcasting automatically (to perform element-wise addition internally)
c = a + b

print("\nTensor C:\n\n", c)
print("\nShape of C:", c.shape, "\n")

Tensor A: tensor([1, 2, 3])
Shape of Tensor A: torch.Size([3])

Tensor B

 tensor([[1],
        [2],
        [3]])

Shape of Tensor B: torch.Size([3, 1])
-----------------------------------------------------------------

Tensor C:

 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

Shape of C: torch.Size([3, 3]) 



### 4.2 Logic & Comparisons

 Logical operations (`&` (AND), `|` (OR)) and comparison operators (`>`, `==`, `<`) allow creating boolean masks to filter, select, or modify data based on specific conditions making these tools powerful for data preparation and analysis.

In [40]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("Temperatures:", temperatures)
print("-" * 50)

# Uses '>' (greater than) to find temperatures above 30
is_hot = temperatures > 30

# Uses '<=' (less than or equal to) to find temperatures 20 or below
is_cool = temperatures <= 20

# Uses '==' (equal to) to find temperatures exactly equal to 35
is_35_degrees = temperatures == 35

print("\nHot (> 30 degreee):", is_hot)
print("Cool (<= 20 degreee):", is_cool)
print("Exactly 35 degreee:", is_35_degrees, "\n")

Temperatures: tensor([20, 35, 19, 35, 42])
--------------------------------------------------

Hot (> 30 degreee): tensor([False,  True, False,  True,  True])
Cool (<= 20 degreee): tensor([ True, False,  True, False, False])
Exactly 35 degreee: tensor([False,  True, False,  True, False]) 



In [41]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("Is Morning:", is_morning)
print("Is Raining:", is_raining)
print("-" * 50)

# Uses '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# Uses '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMorning & (AND) Raining:", morning_and_raining)
print("Morning | (OR) Raining:", morning_or_raining)

Is Morning: tensor([ True, False, False,  True])
Is Raining: tensor([False, False,  True,  True])
--------------------------------------------------

Morning & (AND) Raining: tensor([False, False, False,  True])
Morning | (OR) Raining: tensor([ True, False,  True,  True])


### 4.3 Statistics

Calculating statistics like the mean or standard deviation can be useful for understanding the dataset or for implementing certain types of normalization during the data preparation phase.

**Mean**

In [ ]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print("Data:", data)
print("-" * 45)

# Calculates the mean of all elements in a tensor
data_mean = data.mean()

print("\nCalculated Mean:", data_mean, "\n")

Data: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

Calculated Mean: tensor(30.) 



**Standard Deviation**

In [43]:
print("Data:", data)
print("-" * 45)

# Calculates the standard deviation of all elements.
data_std = data.std()

print("\nCalculated Standard Deviation:", data_std, "\n")

Data: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

Calculated Standard Deviation: tensor(15.8114) 



### 4.4 Data Types

A standard practice to ensure tensors having the correct data type for the model model to avoid runtime errors or unexpected behavior during training.

NOTE: Neural networks typically perform their calculations using 32-bit floating point numbers (float32).

In [44]:
print("Data:", data)
print("Data Type:", data.dtype)
print("-" * 45)

# Casts the tensor to a int type
int_tensor = data.int()

print("\nCasted Data:", int_tensor)
print("Casted Data Type", int_tensor.dtype)

Data: tensor([10., 20., 30., 40., 50.])
Data Type: torch.float32
---------------------------------------------

Casted Data: tensor([10, 20, 30, 40, 50], dtype=torch.int32)
Casted Data Type torch.int32


## Conclusion

Congratulations on completing this lab! You have now worked through the fundamental building blocks of PyTorch. You started with an empty slate and learned to create, reshape, combine, and query tensors in various ways.

The skills you have developed here are essential for every machine learning practitioner. The element-wise arithmetic and broadcasting you practiced are precisely how a neural network efficiently applies weights and biases to entire batches of data at once. The reshaping techniques like `unsqueeze` and `squeeze` are what allow you to prepare a single data point for a model that expects a batch, and then clean up the output afterward. These are not just abstract exercises; they are the day-to-day operations required to build and debug effective deep learning models.

With this solid understanding of tensors, you are now fully prepared to move on to the next stage: building and training neural networks to solve even more complex problems. Every model you build from now on will stand on this foundation.